name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: hotel_admin
          POSTGRES_PASSWORD: hotel_password
          POSTGRES_DB: hotel_database
        ports:
          - 5432:5432
        

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v4
      with:
          name: andersen_hotel
          path: target/*.jar
